// Generated by https://quicktype.io

export interface Posts {
  id: string;
  title: string;
  content: string;
  createdAt: string;
  updatedAt: string;
  userId: string;
  Comment: Comment[];
  user: PostsUser;
}

export interface Comment {
  content: string;
  id: string;
  postId: string;
  createdAt: string;
  user: CommentUser;
}

export interface CommentUser {
  id: string;
  name: string;
  email: string;
  password: string;
  whitelisted: boolean;
}

export interface PostsUser {
  name: string;
  id: string;
}
