// Generated by https://quicktype.io

export interface Teams {
  type: string;
  name: string;
  attributes: Attributes;
  elements: TeamsElement[];
}

export interface Attributes {
  constructorId: string;
  url: string;
}

export interface TeamsElement {
  type: string;
  name: string;
  elements: ElementElementClass[];
}

export interface ElementElementClass {
  type: string;
  text: string;
}
