import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import { NextAuthProvider } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className={inter.className}>
          <Navbar />
          <div className="min-h-screen bg-slate-600 text-white p-6">
            {children}
          </div>
        </body>
      </NextAuthProvider>
    </html>
  );
}
